'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

# fill sequence
seq = [1, 2]
val = seq[-2] + seq[-1]
while val <= 4000000:
    seq.append(val)
    val = seq[-2] + seq[-1]
# calc sum of even numbers <= 4kk
sum = 0
for i in range(1, len(seq), 3): # every 3-rd number is even, because 2 odds result in even number
    sum += seq[i]
print('sum:', sum)